### ISSUE TITLE
broken anchors

### ISSUE THREAD

**Issue by DreadKnight** [scrollback/scrollback#585] opened 2015-04-03 23:58 UTC
I use a lot of anchor links on my website, but recently scrollback kinda ruins their purpose by causing the page to snap a bit and scrolls lower after loading. See example over here, which eventually displays the unit below the targeted one http://ancientbeast.com/units/#Miss_Creeper

**Comment by DreadKnight** [comment] 2015-04-07 23:45
Will have to disable this until fix as I can't properly work with artists, it's like I'm basically linking to the next creature.

**Comment by satya164** [comment] 2015-04-13 07:00
We're on it. It will be fixed in next release. Sorry for the inconvenience.

**Comment by DreadKnight** [comment] 2015-04-13 07:02
Good to hear, cheers! :-)

**Comment by satya164** [comment] 2015-04-14 09:58
The issue is fixed.

**Closed by satya164** 2015-04-14 09:58 UTC
