### ISSUE TITLE
autofocus is broken

### ISSUE THREAD

**Issue by seiyria** [scrollback/scrollback#616] opened 2015-04-12 16:46 UTC
Hi,

A recent update introduced scrollback attempting to take focus from other elements on the page. In my webapp (http://webfe.idle.land) there are some modal dialog boxes that have inputs on them. Scrollback wrongly takes focus from these elements, leaving users unable to type into these boxes. Also, scrollback tries to take focus even if it's hidden which is quite strange and quite honestly undesirable behavior.

**Comment by satya164** [comment] 2015-04-13 06:45
Hi. Thanks for the report. We're on it.

**Comment by satya164** [comment] 2015-04-14 09:58
The issue is fixed on production now.

**Closed by satya164** 2015-04-14 09:58 UTC
