### ISSUE TITLE
Installation issues

### ISSUE THREAD

**Issue by rohitCloud** [scrollback/scrollback#506] opened 2015-02-19 16:26 UTC
Not working facing strange issue. And some issue is also with postgres. no routine errors.![screenshot from 2015-02-19 21 53 18](https://cloud.githubusercontent.com/assets/6195284/6270731/d1270cd0-b881-11e4-82df-c4ecec63214a.png)
![image](https://cloud.githubusercontent.com/assets/6195284/6270752/0e65f610-b882-11e4-9686-d37f1bf3c7ae.png)

**Comment by aravindet** [comment] 2015-02-25 06:57
Hello, please create the postgres tables by running sbentities.sql and sbcontent.sql files. Also, please check if gulp has given any error messages?

The install.sh file should do this, it’s likely outdated. If you plan to use Scrollback in production on your site, may I suggest using the hosted service on scrollback.io? It’s updated weekly and maintained by the authors.

**Comment by aravindet** [comment] 2015-03-03 14:45
Anyway, duplicate of #501

**Closed by aravindet** 2015-03-03 14:45 UTC
