### ISSUE TITLE
No visible scrollbar makes scrolling painful

### ISSUE THREAD

**Issue by dabibbit** [scrollback/scrollback#405] opened 2014-11-25 23:25 UTC
It is extremely painful to scroll either the user list, discussion list or the message area in the Scrollback web interface. The lack of visible vertical scroll bars or scroll arrows makes this a guessing game.

Please add visible scroll bars and scroll arrows to all areas that can be scrolled vertically.

Example problem areas:

A user has to go through the following process to scroll messages:

1) Guess that the message list is actually scrollable. Without a visible scroll bar, this is not clear.
2) Click on a message in the correct location
3) Click on the message a second time to de-select that particular conversation
4) Take their hand off the mouse and use either the page up / page down buttons or up / down arrows to scroll the conversation.

Having to click on the message area to get the focus needed to scroll is problematic because each message already has multiple active areas:

1) The author's name and message itself. Clicking here will begin a response with the @author of the message that was clicked. Clicking this area highlights the discussion that contains that particular message, and makes it impossible to scroll past the top of that particular conversation. 

Users must click a second time to freely scroll with message area with page up/down or the up/down arrows. 

2) The menu icon to the right of the message. Clicking here brings up a menu, whose only current entry is to "Tweet this message."

A user has to go through the following process to scroll the discussion list:

1) The user does not start with the ability to scroll the discussion list, but must first click on a random discussion. This may not be an interesting discussion, but one must be clicked in order for the discussion list to be scrolled. Doing this filters the messages so that only members of this discussion are visible.
2) The user must move their hand off the mouse and use the page up/down buttons or arrow keys to scroll the discussion list.
3) It is not obvious how to scroll messages within a discussion that was filtered from the discussion list. It does not seem to work the same way as when "all discussions" were selected.
4) Once the user selects "All discussions" he loses the ability to scroll the list of discussions

In order to scroll the user list, a user must first click within the user list and then move his hand off of the mouse to use the up / down arrows and page up / down button to scroll the user list. 

This is all very frustrating. Please add visible scroll bars and scroll arrows to all areas that can be scrolled vertically.

**Comment by aravindet** [comment] 2015-01-05 12:39
This will be fixed soon. Sorry about the delay, this was more complex than it looks.

A side effect of the current approach to infinite scrolling is that the scrollbar jumps to the middle as you scroll. This is rather disorienting, which is why scrollbars were hidden. The fix is to write a [new infinite scroll library](/scrollback/endless).

**Comment by satya164** [comment] 2015-04-14 09:59
The issue is no longer relevant.

**Closed by satya164** 2015-04-14 09:59 UTC
